-- what is the total revenue generated by male vs female customers
SELECT gender, SUM(purchase_amount) as revenue
FROM my_table GROUP BY gender

-- which customer used discount but still spend more than the average purchase amount
SELECT customer_id, purchase_amount
FROM my_table
WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) FROM my_table)

-- which are the top 5 products with the highest average review rating
SELECT item_purchased, ROUND(AVG(review_rating), 2) AS 'Average product rating'
FROM my_table
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- compare the average purchase amounts between standard and express shipping
SELECT shipping_type, AVG(purchase_amount)
FROM my_table
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type

-- do subscribed customers spend more? Compare average spend and total revenue between subscriber & non subscribers
SELECT subscription_status,
COUNT(customer_id) AS total_customers,
AVG(purchase_amount) AS avg_spend,
SUM(purchase_amount) AS total_revenue
FROM my_table
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend DESC;

-- which 5 products have highest percentage of purchase with discount applied
SELECT item_purchased,
100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*) AS discount_rate
FROM my_table
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- segment customers into new, returning, and loyal based on their total number of pervious purchases & show the count on each segment
WITH customer_type AS (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning' 
    ELSE 'Loyal' 
    END AS customer_segment
FROM my_table
)
SELECT customer_segment, COUNT(*) AS "Number of customers"
FROM customer_type
GROUP BY customer_segment

-- what are the top 3 most purchased products within each category 
WITH item_counts AS (
SELECT category,
item_purchased,
COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM my_table
GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;

-- are customers who are repeat buyers (more than 5 previous purchases ) aslo likely to subscribe?
SELECT subscription_status,
COUNT(customer_id) AS repeat_buyers
FROM my_table
WHERE previous_purchases > 5
GROUP BY subscription_status


-- what is the revenue contribution of each age group?
SELECT age_group,
SUM(purchase_amount) AS total_revenue
FROM my_table
GROUP BY age_group
ORDER BY total_revenue DESC